--GLPI Chamado - ID: 49642
--PR 9286-2023 CLE 
SET SERVEROUTPUT ON
DECLARE
--declarar variavel tipo number para chama no nextval do primeiro insert 
Vevento_cle NUMBER;
    
BEGIN
--dando valor a variavel, utilizando o nextval  da pr_evento_cle
    Vevento_cle:= SIGS_PROD.PR_EVENTO_CLE_SEQ.NEXTVAL

--Agora eu pego a variavel e substituo onde seria o nextval    
INSERT INTO SIGS_PROD.PR_EVENTO_CLE
(EVCLE_ID, EVCLE_NOME, EVCLE_TPEV_ID, EVCLE_FLAG_AREA, EVCLE_FLAG_PUBLICIDADE, EVCLE_FLAG_ESTRUTURA, EVCLE_FLAG_SONORA, EVCLE_FLAG_BEBIDA, EVCLE_FLAG_ALIMENTO, EVCLE_FLAG_PRODUTO, EVCLE_FLAG_SERVICO, EVCLE_FLAG_MEDICO, EVCLE_FLAG_ANIMAIS, EVCLE_FLAG_PIROTECNICO, EVCLE_FLAG_PARQUE, EVCLE_FLAG_PANFLETO, EVCLE_FLAG_BANHEIRO, EVCLE_FLAG_RESIDUO, EVCLE_FLAG_RES_SECO, EVCLE_FLAG_RES_UMIDO, EVCLE_FLAG_TRANSITO, EVCLE_FLAG_TRANSPORTE, EVCLE_FLAG_MINITRIO, EVCLE_FLAG_COMERCIO, EVCLE_FLAG_SEGPARTICULAR, EVCLE_FLAG_BRIGADISTA, EVCLE_FLAG_ALVARA, EVCLE_FLAG_EMERGENCIA, EVCLE_NUM_ALVARA, EVCLE_ALVARA_VALIDADE, EVCLE_CLE_ID, EVCLE_DESCRICAO, EVCLE_OBSERVACOES, EVCLE_QTD_BRIGADISTA)
VALUES(Vevento_cle, 'IMERSAO INTELIGENCIA EMOCIONAL METODO EVO', 2, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, NULL, NULL, 97176, NULL, NULL, NULL);

--Essa tabela utilizará o id da tabela de cima FK e para relacionar é só passar o a variavel no lugar
INSERT INTO SIGS_PROD.PR_DATA_EVENTO_CLE
(DTCLE_ID, DTCLE_EVCLE_ID, DTCLE_DATA_INI, DTCLE_DATA_FIM, DTCLE_QTD_PUBLICO, DTCLE_CEP_ID, DTCLE_BAIRRO_ID, DTCLE_NUMERO_LOCAL, DTCLE_COMPL_LOCAL, DTCLE_PONTOREFERENCIA)
VALUES(SIGS_PROD.PR_DATA_EVENTO_CLE_SEQ.NEXTVAL, Vevento_cle , TIMESTAMP '2023-06-02 08:00:00.000000', TIMESTAMP '2023-06-04 22:00:00.000000', 3000, 69435, 242, 'S/N', NULL, NULL);


  COMMIT;
END;	
/
