-- 1) Não existem na tabela PR_CONTATO
SELECT C.CONT_ID,C.CONT_CGA,C.CONT_NOME
		 FROM SIGS_PROD.PR_CONTATO C  
		 WHERE c.CONT_CGA IN ('38632000147'); -- TEM CONTATO
------------------------------------------------------------------------------------------------------------------------------------------------------------
--2) Engenho não deferido
SELECT DISTINCT c.CONT_CGA, ENGE_STEN_ID, pse.STEN_DESCRICAO
     FROM SIGS_PROD.PU_ENGENHO E 
     JOIN SIGS_PROD.PR_CONTATO C ON (C.CONT_ID = E.ENGE_CONT_ID) 
     JOIN SIGS_PROD.PU_STATUS_ENGENHO pse ON (e.ENGE_STEN_ID = pse.STEN_ID)
     where ENGE_STEN_ID != 2
     AND e.ENGE_DATA_VALIDADE IS NOT NULL
	 and c.CONT_CGA IN ('38632000147');
----------------------------------------------------------------------------------------------------------------------------------------------------------
--3) Não possui relacionamento TVL (não consta na tabela PU_CONTATO_TVL_BKP)
SELECT distinct c.CONT_CGA, E.ENGE_DATA_VALIDADE
     FROM SIGS_PROD.PU_ENGENHO E 
     JOIN SIGS_PROD.PR_CONTATO C ON (C.CONT_ID = E.ENGE_CONT_ID) 
     --JOIN SIGS_PROD.PU_CONTATO_TVL_BKP CT ON (CT.CTVL_CONT_ID = C.CONT_ID) 
     where ENGE_STEN_ID = 2  -- engenhos deferidos
	 AND  c.CONT_CGA IN ('38632000147')
ORDER BY c.CONT_CGA;
------------------------------------------------------------------------------------------------------------------------------------------------------------
--4) Não possui Viabilidade (tabela AT_VIABILDADE)
SELECT DISTINCT C.CONT_CGA,C.CONT_NOME,E.ENGE_DATA_VALIDADE
     FROM SIGS_PROD.PU_ENGENHO E 
     JOIN SIGS_PROD.PR_CONTATO C ON (C.CONT_ID = E.ENGE_CONT_ID) 
     JOIN SIGS_PROD.PU_CONTATO_TVL_BKP CT ON (CT.CTVL_CONT_ID = C.CONT_ID) 
     --JOIN SIGS_PROD.AT_VIABILIDADE V ON (V.VIAB_ID = CT.CTVL_VIAB_ID) 
     WHERE ENGE_STEN_ID = 2  -- engenhos deferidos
	 AND  c.CONT_CGA IN 
('38632000147')
ORDER BY C.CONT_CGA;

--5) Não são definitivos
SELECT DISTINCT  AA.ANLS_TPVI_ID, ENGE_STEN_ID, C.CONT_ID,C.CONT_CGA,C.CONT_NOME, 
	 SIGS_PROD.GET_ULT_PROC_PUB_VAL_ENG(C.CONT_ID, '03') AS ID_PROC,
	 D.DOCU_NUMERO_DOC,D.DOCU_ANO,D.DOCU_SERV_ID,CI.CEIN_NUMERO, 
     E.ENGE_DATA_VALIDADE,
     AA.ANLS_DT_VENC_VIABILIDADE 
     FROM SIGS_PROD.PU_ENGENHO E 
     JOIN SIGS_PROD.PR_CONTATO C ON (C.CONT_ID = E.ENGE_CONT_ID) 
     JOIN SIGS_PROD.PU_CONTATO_TVL_BKP CT ON (CT.CTVL_CONT_ID = C.CONT_ID) 
     JOIN SIGS_PROD.AT_VIABILIDADE V ON (V.VIAB_ID = CT.CTVL_VIAB_ID) 
     JOIN SIGS_PROD.AT_ANALISEATIV AA ON (AA.ANLS_ID = V.VIAB_ANLS_ID) 
     JOIN SIGS_PROD.PR_DOCUMENTO D ON (D.DOCU_ID = SIGS_PROD.GET_ULT_PROC_PUB_VAL_ENG(C.CONT_ID, '03')) 
     JOIN SIGS_PROD.PR_CENTROINFORMACAO CI ON (CI.CEIN_ID = D.DOCU_CEIN_ID) 
     LEFT JOIN SIGS_PROD.PU_TVL_IMPEDIMENTO_RENOVACAO TI ON TI.TVIM_VIAB_ID = V.VIAB_ID 
     WHERE TRUNC(E.ENGE_DATA_VALIDADE) BETWEEN TO_DATE('01/03'||TO_CHAR(SYSDATE, 'YY'),'DD/MM/YY') AND LAST_DAY(TO_DATE('03'||TO_CHAR(SYSDATE, 'YY'),'MM/YY'))  
     and ENGE_STEN_ID = 2  -- engenhos deferidos
	 -- tvl permanente
	 AND AA.ANLS_TPVI_ID != 1  
	 AND  c.CONT_CGA IN 
('38632000147') 
ORDER BY c.CONT_CGA ;

-- EngenhoDAO 
SELECT DISTINCT C.CONT_ID,C.CONT_CGA,C.CONT_NOME, 
	 SIGS_PROD.GET_ULT_PROC_PUB_VAL_ENG(C.CONT_ID, '03') AS ID_PROC,
	 D.DOCU_NUMERO_DOC,D.DOCU_ANO,D.DOCU_SERV_ID,CI.CEIN_NUMERO, 
     E.ENGE_DATA_VALIDADE,
     AA.ANLS_DT_VENC_VIABILIDADE 
     FROM SIGS_PROD.PU_ENGENHO E 
     JOIN SIGS_PROD.PR_CONTATO C ON (C.CONT_ID = E.ENGE_CONT_ID) 
     JOIN SIGS_PROD.PU_CONTATO_TVL_BKP CT ON (CT.CTVL_CONT_ID = C.CONT_ID) 
     JOIN SIGS_PROD.AT_VIABILIDADE V ON (V.VIAB_ID = CT.CTVL_VIAB_ID) 
     JOIN SIGS_PROD.AT_ANALISEATIV AA ON (AA.ANLS_ID = V.VIAB_ANLS_ID) 
     JOIN SIGS_PROD.PR_DOCUMENTO D ON (D.DOCU_ID = SIGS_PROD.GET_ULT_PROC_PUB_VAL_ENG(C.CONT_ID, '03')) 
     JOIN SIGS_PROD.PR_CENTROINFORMACAO CI ON (CI.CEIN_ID = D.DOCU_CEIN_ID) 
     LEFT JOIN SIGS_PROD.122222222222222PU_TVL_IMPEDIMENTO_RENOVACAO TI ON TI.TVIM_VIAB_ID = V.VIAB_ID 
     WHERE TRUNC(E.ENGE_DATA_VALIDADE) BETWEEN TO_DATE('01/03'||TO_CHAR(SYSDATE, 'YY'),'DD/MM/YY') AND LAST_DAY(TO_DATE('03'||TO_CHAR(SYSDATE, 'YY'),'MM/YY'))  
     and ENGE_STEN_ID = 2  -- engenhos deferidos
	 -- tvl permanente
	 AND AA.ANLS_TPVI_ID = 1  
     AND ((TVIM_ID IS NOT NULL AND TVIM_DATA_REMOVIDO IS NOT NULL) OR TVIM_ID IS NULL)
	 AND C.CONT_FLAG_MERCADO_PUB = 0 
     AND C.CONT_CGA IS NOT NULL 
     AND NOT EXISTS (SELECT 1 FROM SIGS_PROD.PU_RENOV_ENGENHO WHERE REEN_ENGE_ID=ENGE_ID AND TO_CHAR(REEN_DT_RENOVACAO,'YYYYMM') = TO_CHAR(E.ENGE_DATA_VALIDADE,'YYYYMM'))
	 AND  c.CONT_CGA IN ('73935500121','28270500102','73215300119','21800000164','23513200115','73538400158','28129600178','55888100199','64338800176','56236400174');

SELECT * FROM SIGS_PROD.PU_RENOV_ENGENHO re
INNER JOIN SIGS_PROD.PU_ENGENHO pe ON re.REEN_ENGE_ID = pe.ENGE_ID 
INNER JOIN sigs_prod.PR_CONTATO pc ON pe.ENGE_CONT_ID = pc.CONT_ID 
WHERE pc.CONT_CGA = '07265100193';
