/*Ultima movimentação foi errada, então terá que deletar
Processo 6305/2023*/ 

--PRIMEIRA COISA É LOCALIZAR O ID DESSE PROCESSO
SELECT * FROM SIGS_PROD.PR_DOCUMENTO docu
WHERE docu.DOCU_NUMERO_DOC = '6305'
AND   docu.DOCU_ANO = 2023
AND   docu.DOCU_CEIN_ID = (SELECT cein.cein_id FROM SIGS_PROD.PR_CENTROINFORMACAO cein WHERE cein.CEIN_NUMERO ='5911000000');--9589178

-- DEPOIS lOCALIZAR AS DUAS ULTIMAS MOVIMENTAÇÕES
SELECT * FROM SIGS_PROD.PR_MOVIMENTACAO_HISTORICO
WHERE MOHI_DOCU_ID = 9589178
ORDER BY MOHI_ORIGEM_DATAHORA;

--ID DAS DUAS ULTIMAS MOVIMETACAO DA PR_MOV_HIST
--84934719(penultima)
--84945385 (ultima)

--EXCLUINDO AS DUAS ULTIMAS MOVIMENTAÇÕES
DELETE FROM SIGS_PROD.PR_MOVIMENTACAO_HISTORICO
WHERE MOHI_ID IN (84934719,84945385)


--AGORA VAMOS INSERIR A PENULTIMA MOV DA PR_MOV COM NOVO ID, O RESTO DOS DADOS SERÃO OS MESMO, USEI A SEQUENCIA COM NEXTVAL
INSERT INTO SIGS_PROD.PR_MOVIMENTACAO
(MOVI_ID, MOVI_ESTG_ID, MOVI_DOCU_ID, MOVI_ORIGEM_CEIN_ID, MOVI_ORIGEM_USUA_ID, MOVI_ORIGEM_DATAHORA, MOVI_DEST_CEIN_ID, MOVI_DEST_USUA_ID, MOVI_DEST_DATAHORA, MOVI_PARECER_OLD, MOVI_FLAG_CONFIDENCIAL, MOVI_FLAG_RECEBIDO, MOVI_FLAG_SEGUNDA_VIA, MOVI_OPERADO_POR, MOVI_FLAG_GUIA_EMITIDA, MOVI_DIAS_CORRIDOS, MOVI_DIAS_UTEIS, MOVI_TIPOATENDMENTO, MOVI_EMPRESA, MOVI_PARECER)
VALUES(PR_MOVIMENTACAO_SEQ, 190, 9589178, 7527, 1462, TIMESTAMP '2023-05-04 15:06:56.248516', 7456, NULL, TIMESTAMP '2023-05-05 09:27:42.033793', NULL, 0, '1', '1', 373, 0, NULL, NULL, NULL, NULL, 'Para assinatura da Certidão.');
