UPDATE PR_CONSULTA_RISCO
SET CORI_DESC_ATIV_ECONOMICA  = TRANSLATE(CORI_DESC_ATIV_ECONOMICA, 'áéíóúÁÉÍÓÚâêîôûÂÊÎÔÛãõÃÕçÇ', 'aeiouAEIOUaeiouAEIOUaoAOcC');
    
    
UPDATE PR_CONSULTA_RISCO   
SET CORI_RISCO_URBANISTICO  = TRANSLATE(CORI_RISCO_URBANISTICO, 'áéíóúÁÉÍÓÚâêîôûÂÊÎÔÛãõÃÕçÇ', 'aeiouAEIOUaeiouAEIOUaoAOcC');
  

UPDATE PR_CONSULTA_RISCO     
SET CORI_RISCO_SANITARIO  = TRANSLATE(CORI_RISCO_SANITARIO, 'áéíóúÁÉÍÓÚâêîôûÂÊÎÔÛãõÃÕçÇ', 'aeiouAEIOUaeiouAEIOUaoAOcC');	
   

UPDATE PR_CONSULTA_RISCO    
SET CORI_AMBIENTAL_MUNI  = TRANSLATE(CORI_AMBIENTAL_MUNI , 'áéíóúÁÉÍÓÚâêîôûÂÊÎÔÛãõÃÕçÇ', 'aeiouAEIOUaeiouAEIOUaoAOcC');

/*
EXCLUIDO PQ A ALTERAÇÃO FEITA ACIMA NÃO TEVE O RESULTADO ESPERADO. POR EM PRODUÇÃO NÃO ACEITAR UTF-8
E SUBSTITUIR OS CARACTERES DE ACENTUAÇÃO POR "?"
*/
DROP TABLE PR_CONSULTA_RISCO;
    	
