--ambiente de produção
SELECT

SERV.SERV_DESCRICAO AS "TIPO SERVIÇO",

(SELECT NVL(SUM(DAM.DAM_VALOR_FINAL), 0) FROM SIGS_PROD.DA_DAM DAM WHERE DAM.DAM_SERV_ID = SERV.SERV_ID AND DAM.DAM_ANO_EXERCICIO = 2023) AS VALOR_TOTAL

FROM SIGS_PROD.PR_SERVICO SERV

WHERE SERV.SERV_ID IN (697, 924);
