SELECT * FROM SIGS_PROD.DA_DAM;
SELECT * FROM SIGS_PROD.PR_SERVICO;

SELECT min (DAM_DATA_EMISSAO), max (DAM_DATA_EMISSAO) --função retorna menor e maior dados de alguma coisa
FROM SIGS_PROD.DA_DAM;

SELECT MIN (DAM_VALOR_TOTAL_SERVICO), MAX (DAM_VALOR_TOTAL_SERVICO)-- MIN E MAX PARA NUMEROS
FROM SIGS_PROD.DA_DAM;

SELECT COUNT(*)
FROM SIGS_PROD.DA_DAM; --numero total de linhas utilizando (*)

SELECT COUNT (DAM_VALOR_TOTAL_SERVICO) "VALOR TOTAL DOS SERV LINHAS"
FROM SIGS_PROD.DA_DAM;--numero total de linhas utilizando (*) NOMEANDO COLUN, DETALHE NESSE CASO ELA VAI IGNORAR AS LINHAS NULAS E NÃO VAI TRAZER

SELECT AVG(DAM_VALOR_FINAL)
FROM  SIGS_PROD.DA_DAM;

SELECT AVG (NVL(DAM_VALOR_FINAL,0))
FROM  SIGS_PROD.DA_DAM;

SELECT COUNT (NVL(DAM_VALOR_TOTAL_SERVICO,0))
FROM SIGS_PROD.DA_DAM;-- CASO HAJA ALGUMA LINHA COM INFORMAÇÕES NULAS, TAMBÉM SERÁ TRAZIDA UTILIZANDO O NVL QUE TRANSFORMA O NULO EM 0

SELECT COUNT (DISTINCT DAM_VALOR_TOTAL_SERVICO)
FROM SIGS_PROD.DA_DAM; -- RETORNA O NUMERO DE LINHAS QUE NÃO SÃO REPETIDAS

SELECT AVG(DAM_VALOR_TOTAL_SERVICO) --FUNÇÃO DE BUSCAR MÉDIA
FROM SIGS_PROD.DA_DAM;


SELECT AVG(NVL(DAM_VALOR_TOTAL_SERVICO,0))--NVL NOVAMENTO TRANSFORMANDO CAMPOS NULL EM 0 PARA RETORNAR
FROM SIGS_PROD.DA_DAM;

SELECT DAM_ID, AVG(DAM_VALOR_TOTAL_SERVICO)
FROM SIGS_PROD.DA_DAM
WHERE DAM_ANO_EXERCICIO > 2015
GROUP BY DAM_ID
ORDER BY DAM_ID;


SELECT SERV_ID, count(SERV_CEIN_ID)
FROM SIGS_PROD.PR_SERVICO
GROUP BY SERV_ID 
ORDER BY SERV_ID;


